language: ruby
dist: trusty
sudo: false
cache: bundler
rvm:
  - 2.3.1
addons:
  apt:
    packages:
      - vim-gtk
env:
  - TRAVIS_CI=1
before_script:
  - "gem install bundler:1.17.2"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "vim --version"
